jwt:
  secreteKey: lkjsegnosher93847bdvk34y9jvnli3ehfrhdiofhosdnbldslfghosjvosdbvbnsld8749jsjfb

spring:
  application:
    name: api-gateway

#api gateway config
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
#            - RedirectTo=302, https://codingshuttle.com
#            add custom logging filter
            - name: LoggingOrdersFilter
            - name: Authentication
              args:
                isEnabled: true

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, MD

        - id: shipping-service
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/api/v1/shipping/**
          filters:
            - StripPrefix=2



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#server:
#  port: 9090

