spring:
  application:
    name: shipping-service


server:
  port: 9040


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  register-with-eureka: true
  fetch-registry: true


resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 100ms
