# actuator config
management:
    health:
      circuitbreakers:
       enabled: true
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always


resilience4j:
  retry:
    instance:
      inventoryRetry:
        maxRetryAttempts: 4
        waitDuration: 20s

  ratelimiter:
    instance:
      inventoryRateLimiter:
        limiteForPeriod: 1
        limiteRefreshPeriod: 5s
        timeoutDuration: 2s

  circuitbreaker:
    instances:
      inventory FeignClient:
        register-health-indicator: true # Enables health indicator for this circuit breaker in Actuator (/actuator/health)
        sliding-window-size: 10         # Number of calls used to calculate the failure rate (only the latest 10 calls are considered)
        failure-rate-threshold: 50      # If 50% or more of the calls in the sliding window fail, the circuit breaker opens
        wait-duration-in-open-state: 10000 # Time (in milliseconds) the circuit breaker stays open before transitioning to half-open state (10 seconds)
        permitted-number-of-calls-in-half-open-state: 5 # Number of trial calls allowed when the circuit breaker is in half-open state
        sliding-window-type: COUNT_BASED # Uses count-based sliding window (alternative is TIME_BASED)
        minimum-number-of-calls: 5       # Circuit breaker will only calculate failure rate after at least 5 calls
        automatic-transition-from-open-to-half-open-enabled: true # Automatically moves to half-open state after the wait duration elapses




# max retry :- maximum time try to get data from trigger api but if not then fail.
# waitDuration :- wait for given time after that again call that api.
